name: Assign Reviewers
on:
  pull_request:
    types: [opened]
jobs:
  assign-reviewers:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    outputs:
      telegram_reviewers: ${{ steps.prepare.outputs.telegram_reviewers }}

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Prepare reviewers
        id: prepare
        run: |
          GITHUB_REVIEWERS_MAP="${{ secrets.REVIEWERS_MAP }}"
          github_list=()
          GITHUB_ACTOR="${{ github.event.pull_request.user.login }}"
          readonly PAIR_SEPARATOR='='
          readonly GITHUB_SEPARATOR=','

          decoded_json=$(echo "$GITHUB_REVIEWERS_MAP" | base64 --decode)

          while IFS="${PAIR_SEPARATOR}" read -r github_username _; do

            if [[ "${GITHUB_ACTOR}" != "${github_username}" ]]; then
              github_list+=("\"${github_username}\"")
            fi

          done < <(echo "$decoded_json" | jq -r 'to_entries[] | "\(.key)=\(.value)"')

          github_json="$(IFS="${GITHUB_SEPARATOR}"; echo "[${github_list[*]}]")"

          echo "github_reviewers=${github_json}" >> "$GITHUB_OUTPUT"

      - name: Assign Reviewers
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ steps.prepare.outputs.github_reviewers }}
