name: Notify

on:
  workflow_call:
    inputs:
      lint:
        required: true
        type: string
      format:
        required: true
        type: string
      test:
        required: true
        type: string
      build:
        required: true
        type: string
      coverage:
        required: false
        type: string
      deployUrl:
        required: false
        type: string
      prTitle:
        required: true
        type: string
      refName:
        required: true
        type: string
      prNumber:
        required: true
        type: string
      runID:
        required: true
        type: string
      serverUrl:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      TG_BOT_TOKEN:
        required: true
      TG_CHAT_ID:
        required: true

jobs:
  set-message:
    runs-on: ubuntu-latest
    outputs:
      textMessage: ${{ steps.telegram-message.outputs.textMessage }}
      prMessage: ${{ steps.pr-message.outputs.prMessage }}
    steps:
      - uses: actions/checkout@v4

      - name: Set telegram message
        env:
          DEPLOY_URL: ${{ inputs.deployUrl }}
          PR_TITLE: ${{ inputs.prTitle }}
          REF_NAME: ${{ inputs.refName }}
          SERVER_URL: ${{ inputs.serverUrl }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ inputs.runID }}
          BUILD_RESULT: ${{ inputs.build }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        id: telegram-message
        run: .github/scripts/format-telegram-message.sh

      - name: Set PR message
        env:
          LINT_RESULT: ${{ inputs.lint }}
          FORMAT_RESULT: ${{ inputs.format }}
          TEST_RESULT: ${{ inputs.test }}
          BUILD_RESULT: ${{ inputs.build }}
          TEST_COVERAGE: ${{ inputs.coverage }}
          DEPLOY_URL: ${{ inputs.deployUrl }}
        id: pr-message
        run: .github/scripts/format-pr-message.sh

  notify-telegram:
    needs: set-message
    if: always()
    uses: ./.github/workflows/notify-telegram.yml
    with:
      textMessage: ${{ needs.set-message.outputs.textMessage }}
    secrets:
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}

  update-pr:
    needs: set-message
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update PR description
        id: fetch-body
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          PR_NUMBER: ${{ inputs.prNumber }}
          REPO: ${{ github.repository }}
          BODY_UPDATE: ${{ needs.set-message.outputs.prMessage }}
        run: .github/scripts/update-pr.sh

