name: Notify

on:
  workflow_call:
    inputs:
      lint:
        required: true
        type: string
      format:
        required: true
        type: string
      test:
        required: true
        type: string
      build:
        required: true
        type: string
      coverage:
        required: false
        type: string
      deployUrl:
        required: false
        type: string
      prTitle:
        required: true
        type: string
      refName:
        required: true
        type: string
      prNumber:
        required: true
        type: string
      runID:
        required: true
        type: string
      serverUrl:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      TG_BOT_TOKEN:
        required: true
      TG_CHAT_ID:
        required: true

jobs:
  set-message:
    runs-on: ubuntu-latest
    outputs:
      textMessage: ${{ steps.telegram-message.outputs.textMessage }}
      prMessage: ${{ steps.pr-message.outputs.prMessage }}
    steps:
      - name: Set telegram message
        id: telegram-message
        env:
          DEPLOY_URL: ${{ inputs.deployUrl }}
          PR_TITLE: ${{ inputs.prTitle }}
          REF_NAME: ${{ inputs.refName }}
          SERVER_URL: ${{ inputs.serverUrl }}
          REPOSITORY: ${{ inputs.repository }}
          RUN_ID: ${{ inputs.runID }}
          BUILD_RESULT: ${{ inputs.build }}

        run: |
          SUCCESS_MSG="✅ Deploy succeed [link](${DEPLOY_URL})
          message: ${PR_TITLE}"

          FAILURE_MSG="❌ Deploy failed on branch **${REF_NAME}**\\.
          [View logs](${SERVER_URL}/${REPOSITORY}/actions/runs/${RUN_ID})"

          if [ "$BUILD_RESULT" = "success" ]; then
            echo "textMessage<<EOF" >> $GITHUB_OUTPUT
            echo "$SUCCESS_MSG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "textMessage<<EOF" >> $GITHUB_OUTPUT
            echo "$FAILURE_MSG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Set PR message
        env:
          LINT_RESULT: ${{ inputs.lint }}
          FORMAT_RESULT: ${{ inputs.format }}
          TEST_RESULT: ${{ inputs.test }}
          BUILD_RESULT: ${{ inputs.build }}
          TEST_COVERAGE: ${{ inputs.coverage }}
          DEPLOY_URL: ${{ inputs.deployUrl }}
        id: pr-message
        run: |
          LINT_ICON=$( [ "$LINT_RESULT" = "success" ] && echo "✅" || echo "❌" )
          FORMAT_ICON=$( [ "$FORMAT_RESULT" = "success" ] && echo "✅" || echo "❌" )
          TEST_ICON=$( [ "$TEST_RESULT" = "success" ] && echo "✅" || echo "❌" )
          BUILD_ICON=$( [ "$BUILD_RESULT" = "success" ] && echo "✅" || echo "❌" )

          DEPLOY_LINE=$([ "$BUILD_RESULT" = "success" ] && echo "🚀 [Deploy preview](${DEPLOY_URL})" || echo "")
          TEST_LINE=$([ "TEST_RESULT" = "success" ] && ${TEST_COVERAGE} || echo "")

          SUMMARY="### CI/CD Status
          - ${LINT_ICON} Linter
          - ${FORMAT_ICON} Formatter
          - ${TEST_ICON} Tests
          - ${BUILD_ICON} Build

          ${DEPLOY_LINE}
          ${TEST_COVERAGE}
          ${TEST_LINE}
          "

          echo "prMessage<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  notify-telegram:
    needs: set-message
    if: always()
    uses: ./.github/workflows/notify-telegram.yml
    with:
      textMessage: ${{ needs.set-message.outputs.textMessage }}
    secrets:
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}

  update-pr:
    needs: set-message
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update PR description
        id: fetch-body
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          PR_NUMBER: ${{ inputs.prNumber }}
          REPO: ${{ github.repository }}
        run: |
            CURRENT_BODY=$(curl -s \
          -H "Authorization: token ${GH_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}" \
          | jq -r '.body // ""')


          curl -s -X PATCH \
          -H "Authorization: token ${GH_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}" \
          -d "$(jq -n \
                --arg body "$CURRENT_BODY"$'\n\n---\n'"$BODY_UPDATE" \
                '{body: $body}')"
