name: Build and Deploy to Netlify Production

on:
  push:
    branches:
      - deploy

jobs:
  build:
    uses: ./.github/workflows/netlify.yml
    with:
      isProduction: true
      deployMessage: '${{  github.event.pull_request.title }}'
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      TG_CHAT_ID: ${{secrets.TG_PREVIEW_CHAT_ID}}
      TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
