name: Build and Deploy to Netlify Production

on:
  push:
    branches:
      - deploy

jobs:
  build:
    uses: ./.github/workflows/netlify.yml
    with:
      isProduction: true
      deployMessage: '${{  github.event.pull_request.title }}'
    secrets:
      TG_CHAT_ID: ${{secrets.TG_PROD_CHAT_ID}}
