name: Build and Deploy to Netlify Preview

on:
  push:
    branches:
      - 'feat/**'
      - 'test/**'
      - 'sprint-*'

jobs:
  build:
    uses: ./.github/workflows/netlify.yml
    with:
      isProduction: false
      deployMessage: "${{  github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message || 'No message found' }}"
    secrets:
      TG_CHAT_ID: ${{secrets.TG_PREVIEW_CHAT_ID}}
