name: Build and Deploy to Netlify

on:
  workflow_call:
    inputs:
      isProduction:
        required: true
        type: boolean
      deployMessage:
        required: true
        type: string
      NETLIFY_AUTH_TOKEN:
        required: true
        type: string
    secrets:
      TG_CHAT_ID:
        required: true
      #      NETLIFY_AUTH_TOKEN:
      #        required: true
      NETLIFY_SITE_ID:
        required: true
      TG_BOT_TOKEN:
        required: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Netlify (Preview)
        id: netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./dist
          production-branch: develop
          production-deploy: ${{ inputs.isProduction }}
          deploy-message: ${{ inputs.deployMessage }}
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          netlify-config-path: ./netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    outputs:
      deploy-url: ${{ steps.netlify.outputs.deploy-url }}

  notify:
    needs: build
    if: success()
    uses: ./.github/workflows/notify-telegram.yml
    with:
      textMessage: '✅ link: ${{ needs.build.outputs.deploy-url }}, message: ${{inputs.deployMessage}}'
    secrets:
      TG_CHAT_ID: ${{secrets.TG_CHAT_ID}}
      TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}

  notify-failure:
    needs: build
    if: failure() || needs.build.outputs.deploy-url == ''
    uses: ./.github/workflows/notify-telegram.yml
    with:
      textMessage: "❌ Deploy failed on branch *${{ github.ref_name }}*.\n[View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    secrets:
      TG_CHAT_ID: ${{secrets.TG_CHAT_ID}}
      TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
