name: Notify on Review Requested

on:
  pull_request:
    types:
      - review_requested

jobs:
  notify-reviewer:
    uses: ./.github/workflows/notify-review.yml
    with:
      github_login: ${{ github.event.requested_reviewer.login }}
      text_template: |
        🔔 Review **requested**
        Title: ${{ github.event.pull_request.title }}
        👉 [View PR](${{ github.event.pull_request.html_url }})
    secrets:
      REVIEWERS_MAP: ${{ secrets.REVIEWERS_MAP }}
      TG_CHAT_ID: ${{ secrets.TG_PR_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
