name: Notify on Review Submitted
on:
  pull_request_review:
    types: [ submitted ]

jobs:
  notify-reviewer:
    uses: ./.github/workflows/notify-review.yml
    with:
      github_login: ${{ github.event.pull_request.user.login }}
      text_template: |
        📝Review *submitted*
        Branch: ${{ github.head_ref }}
        Change state to *${{github.event.review.state}}*
        👉 ${{ github.event.pull_request.html_url }}
    secrets:
      REVIEWERS_MAP: ${{ secrets.REVIEWERS_MAP }}
      TG_CHAT_ID: ${{ secrets.TG_PR_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
